// The narration, in both languages. Kept out of the recorder so the wording can
// be argued about without touching the machinery that verifies it.
export const SCRIPT = {
  en: {
    dir: 'ltr',
    font: '"IBM Plex Sans","Helvetica Neue",Arial,sans-serif',
    title: {
      eyebrow: 'NUFI TEAM · ON-PREM AI APPLIANCE',
      head: 'One box. The department&rsquo;s work stays inside it.',
      sub: ['A shared drive, an assistant that answers from your own documents,',
            'and a wall that is enforced rather than promised.',
            'Every answer in this recording is live.'],
    },
    arch: {
      eyebrow: 'HOW IT IS WIRED',
      head: 'Two products, one seam.',
      sub: ['MeshBox is the box: network, portal, drives, console. It runs no model.',
            'NuFi is the AI. Three adapters translate between them &mdash; that is the whole integration.'],
    },
    seam: {
      head: 'The seam, answering for itself.',
      body: 'Each adapter reports what it is really talking to. Nothing here is configured optimism.',
      cap: ['Three adapters, three upstreams.',
            'Chat and RAG reach a model on this machine; the agent reaches a flow engine on this machine.'],
    },
    status: {
      head: 'The console will not flatter the box.',
      cap: ['available, and only because it answered a probe.',
            'An unwired module reads not_connected. There is no configured green here.'],
    },
    connect: {
      eyebrow: 'THE PART THAT HAS TO BE EASY',
      head: 'A laptop joins the way it should &mdash; once, and by double-click.',
      sub: ['An admin registers the machine in the console and hands over one file.',
            'The private key is made on the laptop and never leaves it.'],
      cap: ['One registration, one file.',
            'macOS gets meshbox-connect.command, Windows a .cmd. No keys to paste, no VPN client to configure.'],
      honest: ['This box is running on placeholder keys, and the connector says so.',
               'It refuses to pretend a tunnel it cannot make &mdash; the same honesty as the rest of the box.'],
    },
    drive: {
      head: 'The work already lives on the drive.',
      cap: ['Eight departments, eight shares.',
            'The same folder a laptop mounts as a network drive &mdash; and the same folder the AI answers from.'],
      upload: ['A contract-review guide, uploaded to the 법무 share.',
               'From here it is two things at once: a file colleagues can open, and knowledge the box can answer from.'],
    },
    chat: {
      head: 'The chat tool, for the writing nobody enjoys.',
      cap: ['&ldquo;Draft a two-sentence internal notice: September security training.&rdquo;',
            'Ordinary desk work &mdash; drafting, translating, summarising. The conversation stays on the box.'],
      done: ['Drafted, on this machine.',
             'No document, no draft, and no prompt left the department network to produce this.'],
    },
    agent: {
      head: 'Agents, for the work that repeats.',
      cap: ['Six routines ship with the box; one is running now.',
            'Meeting minutes, morning mail, the weekly report &mdash; built once, then shared by the whole department.'],
      honest: ['Today a routine is triggered by name.',
               'Wiring one to a specific meeting or folder is the next step, and it is an appliance-side change, not a model one.'],
    },
    breadth: {
      eyebrow: 'HOW WIDE THIS GOES',
      head: 'Eight departments. Thirty-two checks. All passing.',
      sub: ['&#48277;&#47924; &middot; &#51064;&#49324; &middot; &#52509;&#47924; &middot; &#51204;&#47844;&#44823;&#54925; &middot; &#51116;&#47924; &middot; &#50689;&#50629; &middot; &#44256;&#44061;&#51648;&#50896; &middot; &#44060;&#48156;',
            'Every stated fact returned with its source; every question outside the documents declined.',
            'Two runs of the whole suite differ in none of the thirty-two answers.'],
    },
    ask: {
      head: 'Ask the box about your own policy.',
      cap: ['&ldquo;What is the single-transaction limit on the corporate card?&rdquo;',
            'Asked in Korean, as the department would. The answer must come from the uploaded document.'],
      done: ['Answered from the department&rsquo;s own policy.',
             'The model ran on this machine. The document never left the box to be read.'],
    },
    refuse: {
      head: 'Now ask something the documents do not cover.',
      cap: ['&ldquo;Where do I return my laptop when I leave?&rdquo;',
            'Nothing on this box says. This is the question that separates a useful box from a dangerous one.'],
      done: ['It declines instead of inventing.',
             'For Legal or HR, a confident wrong answer is worse than no answer at all.'],
    },
    wall: {
      eyebrow: 'THE PART A BUYER SHOULD TEST',
      head: 'The wall is enforced, not promised.',
      sub: ['Same adapter, same department text, pointed at a public destination.'],
      cap: ['403. The software will not carry it off the mesh.',
            'Not a sentence in a brochure &mdash; a refusal you can reproduce with one request.'],
    },
    close: {
      eyebrow: 'WHAT YOU JUST WATCHED',
      head: 'Answers from your documents. Refusals you can trust.',
      sub: ['Eight departments, thirty-two checks, all passing &mdash; and two runs that differ in none of them.',
            'The transcript is committed next to this recording.'],
    },
  },
  ko: {
    dir: 'ltr',
    font: '"IBM Plex Sans KR","Apple SD Gothic Neo","Malgun Gothic",sans-serif',
    title: {
      eyebrow: 'NUFI TEAM · 부서 협업 AI 어플라이언스',
      head: '박스 한 대. 부서의 일이 그 안에서 끝납니다.',
      sub: ['공유 드라이브, 우리 문서로 답하는 도우미,',
            '그리고 말이 아니라 실제로 집행되는 경계.',
            '이 영상의 모든 답변은 실제 실행 결과입니다.'],
    },
    arch: {
      eyebrow: '어떻게 연결되어 있나',
      head: '두 제품, 하나의 이음매.',
      sub: ['MeshBox는 박스입니다 &mdash; 네트워크, 포털, 드라이브, 콘솔. 추론은 하지 않습니다.',
            'NuFi가 AI입니다. 어댑터 3개가 둘 사이를 번역합니다. 통합은 그게 전부입니다.'],
    },
    seam: {
      head: '이음매가 스스로 답합니다.',
      body: '각 어댑터는 자기가 실제로 무엇과 대화하는지 보고합니다.',
      cap: ['어댑터 3개, 상대 3개.',
            'Chat과 RAG는 이 장비의 모델에, 에이전트는 이 장비의 플로우 엔진에 닿습니다.'],
    },
    status: {
      head: '콘솔은 박스를 미화하지 않습니다.',
      cap: ['available &mdash; 프로브에 실제로 응답했기 때문입니다.',
            '연결되지 않은 모듈은 not_connected로 표시됩니다. 설정만으로 켜지는 초록은 없습니다.'],
    },
    connect: {
      eyebrow: '쉬워야만 하는 부분',
      head: '노트북은 한 번, 더블클릭으로 붙습니다.',
      sub: ['관리자가 콘솔에서 기기를 등록하고 파일 하나를 건네줍니다.',
            '개인키는 노트북에서 만들어지고 기기를 떠나지 않습니다.'],
      cap: ['등록 한 번, 파일 하나.',
            'macOS는 meshbox-connect.command, Windows는 .cmd. 붙여넣을 키도, 설정할 VPN 클라이언트도 없습니다.'],
      honest: ['이 박스는 예시 키로 돌고 있고, 커넥터가 그 사실을 스스로 밝힙니다.',
               '만들 수 없는 터널을 만든 척하지 않습니다 &mdash; 박스의 나머지와 같은 정직함입니다.'],
    },
    drive: {
      head: '일은 이미 드라이브에 있습니다.',
      cap: ['8개 부서, 8개 공유함.',
            '노트북이 네트워크 드라이브로 붙는 그 폴더가, AI가 근거로 삼는 그 폴더입니다.'],
      upload: ['계약검토 가이드를 법무 공유함에 올립니다.',
               '이 순간부터 두 가지입니다 &mdash; 동료가 여는 파일이자, 박스가 근거로 답하는 지식.'],
    },
    chat: {
      head: '아무도 즐겁지 않은 글쓰기를 위한 채팅.',
      cap: ['&ldquo;9월 정기 보안교육 안내 공지문을 두 문장으로 써줘.&rdquo;',
            '작성·번역·요약 같은 평범한 실무. 대화는 박스 안에 머뭅니다.'],
      done: ['이 장비에서 작성했습니다.',
             '문서도, 초안도, 프롬프트도 부서 네트워크를 나가지 않았습니다.'],
    },
    agent: {
      head: '반복되는 일을 위한 에이전트.',
      cap: ['루틴 6종이 기본 탑재되어 있고, 지금 하나가 실행됩니다.',
            '회의록, 아침 메일, 주간보고 &mdash; 한 번 만들면 부서 전체가 함께 씁니다.'],
      honest: ['지금은 루틴을 이름으로 호출합니다.',
               '특정 회의나 폴더에 연결하는 것이 다음 단계이며, 모델이 아니라 어플라이언스 쪽 변경입니다.'],
    },
    breadth: {
      eyebrow: '어디까지 넓어지나',
      head: '8개 부서, 32개 확인, 전부 통과.',
      sub: ['법무 &middot; 인사 &middot; 총무 &middot; 전략기획 &middot; 재무 &middot; 영업 &middot; 고객지원 &middot; 개발',
            '문서에 있는 사실은 출처와 함께, 문서에 없는 질문은 거절로.',
            '전체를 두 번 돌려도 32개 답변이 하나도 달라지지 않았습니다.'],
    },
    ask: {
      head: '우리 규정을 박스에 물어봅니다.',
      cap: ['&ldquo;법인카드 1회 사용 한도는 얼마인가요?&rdquo;',
            '답은 반드시 업로드한 문서에서 나와야 합니다.'],
      done: ['부서 자기 문서에서 답했습니다.',
             '추론은 이 장비에서 돌았습니다. 문서는 답을 얻기 위해 박스를 떠나지 않았습니다.'],
    },
    refuse: {
      head: '이번엔 문서에 없는 것을 물어봅니다.',
      cap: ['&ldquo;퇴사할 때 노트북은 어디에 반납하나요?&rdquo;',
            '이 박스의 어떤 문서에도 없습니다. 쓸모 있는 박스와 위험한 박스를 가르는 질문입니다.'],
      done: ['지어내지 않고 모른다고 답합니다.',
             '법무·인사에서는 자신 있게 틀린 답이 답이 없는 것보다 나쁩니다.'],
    },
    wall: {
      eyebrow: '구매자가 직접 확인해야 할 부분',
      head: '경계는 약속이 아니라 집행입니다.',
      sub: ['같은 어댑터, 같은 부서 문장, 목적지만 외부로.'],
      cap: ['403. 소프트웨어가 메시 밖으로 실어 나르지 않습니다.',
            '소개서의 한 문장이 아니라, 요청 한 번으로 재현되는 거절입니다.'],
    },
    close: {
      eyebrow: '방금 보신 것',
      head: '우리 문서에서 나온 답변, 믿을 수 있는 거절.',
      sub: ['8개 부서, 32개 확인 전부 통과 &mdash; 두 번 실행해도 답변이 하나도 달라지지 않았습니다.',
            '실행 기록은 이 영상 옆에 함께 커밋되어 있습니다.'],
    },
  },
};
