#!/bin/bash
# NuFi box — join file for @MEMBER@. Generated by `nufi-box invite`.
set -e
echo "NuFi box -- join for @MEMBER@"
echo "This trusts the box's certificate, connects Tailscale, maps your department drives, and opens chat."
echo "The key inside this file is single-use -- once you run it, ask the admin to invite you again for a new one."
echo

if ! command -v tailscale >/dev/null 2>&1; then
  echo "Tailscale is not installed. Install it from https://tailscale.com/download/linux and run this file again."
  exit 2
fi

CA_B64="@CA_B64@"
TMP_CA="$(mktemp /tmp/nufi-box-ca.XXXXXX).crt"
printf '%s' "$CA_B64" | base64 -d > "$TMP_CA"
echo "Trusting the box's certificate (sudo password may be requested)..."
sudo cp "$TMP_CA" /usr/local/share/ca-certificates/nufi-box.crt
sudo update-ca-certificates

echo "Connecting to the NuFi mesh..."
sudo tailscale login --login-server=@MESH_SERVER_URL@ --auth-key=@AUTH_KEY@ --accept-dns

echo "Mapping your department drives (best effort)..."
@DRIVES@

echo "Opening chat..."
xdg-open "https://@BOX_MESH_HOST@:3080" 2>/dev/null || echo "Open https://@BOX_MESH_HOST@:3080 in your browser."

echo "Done. This key was single-use -- it will not work again."
