#!/bin/bash
# NuFi box — join file for @MEMBER@. Generated by `nufi-box invite`.
set -e
echo "NuFi box -- join for @MEMBER@"
echo "This trusts the box's certificate, connects Tailscale, maps your department drives, and opens chat."
echo "The key inside this file is single-use -- once you run it, ask the admin to invite you again for a new one."
echo

TS="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
if [ ! -x "$TS" ]; then
  echo "Tailscale is not installed. Download it from https://tailscale.com/download/mac and run this file again."
  exit 2
fi

CA_B64="@CA_B64@"
TMP_CA="$(mktemp -t nufi-box-ca).crt"
printf '%s' "$CA_B64" | base64 -D > "$TMP_CA"
echo "Trusting the box's certificate (you may be asked for your password)..."
security add-trusted-cert -r trustRoot -k ~/Library/Keychains/login.keychain-db "$TMP_CA"

echo "Connecting to the NuFi mesh..."
"$TS" login --login-server=@MESH_SERVER_URL@ --auth-key=@AUTH_KEY@ --hostname=@MEMBER@ --accept-dns

echo "Mapping your department drives..."
@DRIVES@

echo "Opening chat..."
open "https://@BOX_MESH_HOST@:3080"

echo "Done. This key was single-use -- it will not work again."
