@echo off
rem NuFi box -- join file for @MEMBER@. Generated by `nufi-box invite`.
setlocal
echo NuFi box -- join for @MEMBER@
echo This trusts the box's certificate, connects Tailscale, maps your department drives, and opens chat.
echo The key inside this file is single-use -- once you run it, ask the admin to invite you again for a new one.
echo.

set "TS=%ProgramFiles%\Tailscale\tailscale.exe"
if not exist "%TS%" (
  echo Tailscale is not installed. Download it from https://tailscale.com/download/windows and run this file again.
  exit /b 2
)

echo Writing and trusting the box's certificate...
echo @CA_B64@>"%TEMP%\nufi-box-ca.b64"
certutil -decode "%TEMP%\nufi-box-ca.b64" "%TEMP%\nufi-box-ca.crt" >nul
certutil -addstore -f Root "%TEMP%\nufi-box-ca.crt" >nul

echo Connecting to the NuFi mesh...
"%TS%" login --login-server=@MESH_SERVER_URL@ --auth-key=@AUTH_KEY@ --hostname=@MEMBER@ --accept-dns

echo Mapping your department drives...
@DRIVES@

echo Opening chat...
start "" "https://@BOX_MESH_HOST@:3080"

echo Done. This key was single-use -- it will not work again.
endlocal
